### ISSUE TITLE
Mutates original object

### ISSUE THREAD

**Issue by srolija** [vkarpov15/mongo-sanitize#1]
I think it should be either noted in the documentation that this library will mutate provided object (especially since it would be expected that it will be query arguments). Or it should return a new object with copied properties.

The current demo example would suggest that it returns a new object rather than mutating original.

Simple code example that shows mutation:

```
const sanitize = require('mongo-sanitize');

const query = {
    name: "example",
    age: {
        "$gt": "",
    }
}

console.log(query);
const clean = sanitize(query.age);
console.log(query);
```

Produces following output:
```
{ name: 'example', age: { '$gt': '' } }
{ name: 'example', age: {} }
```

**Comment by vkarpov15** [comment]
Fixed, thanks for the suggestion :+1:
